"""Renders a future plan to PDF (design.md §2.1, §6, FR-5.10).

Design.md proposed WeasyPrint or ReportLab; WeasyPrint needs native
GTK/Pango/Cairo libraries that aren't available on every dev machine (this one
included), so this uses ReportLab, which is pure Python.
"""

from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

PLAN_PDF_DIR = Path("generated/plans")


def render_plan_pdf(plan_id: int, content: dict) -> str:
    """Renders `content` (the JSON produced by plan_generator.generate_plan) to
    PDF and returns the stored file path."""

    PLAN_PDF_DIR.mkdir(parents=True, exist_ok=True)
    out_path = PLAN_PDF_DIR / f"plan-{plan_id}.pdf"

    styles = getSampleStyleSheet()
    story = [Paragraph(f"Future Plan #{plan_id}", styles["Title"]), Spacer(1, 12)]

    ai_summary = content.get("ai_summary")
    if ai_summary:
        story.append(Paragraph("AI summary", styles["Heading2"]))
        if ai_summary.get("narrative"):
            story.append(Paragraph(ai_summary["narrative"], styles["BodyText"]))
        for note in ai_summary.get("agronomic_notes", []):
            story.append(Paragraph(f"&bull; {note}", styles["BodyText"]))
        if ai_summary.get("finance_commentary"):
            story.append(Paragraph(ai_summary["finance_commentary"], styles["BodyText"]))
        story.append(Paragraph(
            "<i>Generated by an AI model (DeepSeek) from the figures below - verify before acting on it.</i>",
            styles["BodyText"],
        ))
        story.append(Spacer(1, 12))

    timeline = content.get("timeline", {})
    story.append(Paragraph("Timeline", styles["Heading2"]))
    story.append(Paragraph(
        f"Sow: {timeline.get('sow_date', '-')} &rarr; "
        f"Harvest: {timeline.get('harvest_date', '-')} "
        f"({timeline.get('days_to_harvest', '-')} days)",
        styles["BodyText"],
    ))
    story.append(Spacer(1, 12))

    heuristics = content.get("heuristics", [])
    if heuristics:
        story.append(Paragraph("Guidance", styles["Heading2"]))
        for tip in heuristics:
            story.append(Paragraph(f"&bull; {tip}", styles["BodyText"]))
        story.append(Spacer(1, 12))

    soil_effect = content.get("soil_effect", {})
    if soil_effect:
        story.append(Paragraph("Effect on soil", styles["Heading2"]))
        rows = [["", "Current", "Target", "Projected post-harvest"]]
        current = soil_effect.get("current", {})
        target = soil_effect.get("target", {})
        projected = soil_effect.get("projected_post_harvest", {})
        for key in ("n", "p", "k", "ph"):
            rows.append([key.upper(), current.get(key, "-"), target.get(key, "-"), projected.get(key, "-")])
        table = Table(rows, hAlign="LEFT")
        table.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
        ]))
        story.append(table)
        story.append(Spacer(1, 12))

    amendments = content.get("amendments", [])
    if amendments:
        story.append(Paragraph("Recommended amendments", styles["Heading2"]))
        rows = [["Nutrient", "Action", "Amount", "Cost"]]
        for a in amendments:
            amount = a.get("amount_kg_per_ha", a.get("amount_units", "-"))
            rows.append([a["nutrient"].upper(), a["action"], amount, f"${a['cost']:.2f}"])
        table = Table(rows, hAlign="LEFT")
        table.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
        ]))
        story.append(table)
        story.append(Spacer(1, 12))

    finances = content.get("finances", {})
    if finances:
        story.append(Paragraph("Potential yields / finances", styles["Heading2"]))
        rows = [
            ["Estimated yield", f"{finances.get('estimated_yield', 0):.2f}"],
            ["Revenue", f"${finances.get('revenue', 0):.2f}"],
            ["Crop cost", f"${finances.get('crop_cost', 0):.2f}"],
            ["Amendment cost", f"${finances.get('amendment_cost', 0):.2f}"],
            ["Margin", f"${finances.get('margin', 0):.2f}"],
        ]
        table = Table(rows, hAlign="LEFT")
        table.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
        ]))
        story.append(table)

    doc = SimpleDocTemplate(str(out_path), pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    doc.build(story)

    return str(out_path)
